apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zenoffice-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/MassouAnas/manifets.git"
    targetRevision: HEAD
    path: dev
  destination:
    server: "https://kubernetes.default.svc"
    namespace: zenoffice
  syncPolicy:
    automated: # Automatically sync the application on changes
      prune: true # Prune resources when not defined in Git
      selfHeal: true # Automatically sync if drift is detected
    syncOptions:
      - CreateNamespace=true # Automatically create the target namespace if it doesn't exist
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: mongodb
      namespace: zenoffice
      jsonPointers:
        - /spec/replicas
    - group: apps
      kind: Deployment
      name: express-app
      namespace: zenoffice
      jsonPointers:
        - /spec/replicas
    - group: apps
      kind: Deployment
      name: angular-frontend
      namespace: zenoffice
      jsonPointers:
        - /spec/replicas # Ignore differences in the replicas field
