apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: express-app-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: "expressapp"
