apiVersion: v1
kind: PersistentVolume
metadata:
  name: express-app-pv0
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "expressapp"
  hostPath:
    path: /home/ubuntu/zenoffice/logs
