apiVersion: v1
kind: Service
metadata:
  name: express-app
spec:
  type: NodePort
  ports:
    - name: "backend"
      port: 3000
      targetPort: 3000
      nodePort: 30000
    - name: "metrics"
      port: 9100
      targetPort: 9100
      nodePort: 31000
  selector:
    app: express-app
