apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-cm1
data:
  init-mongo.js: |
    db = db.getSiblingDB("mydatabase");

     db.createUser({
      user: "user123",
      pwd: "password123",
      roles: [
        {
          role: "readWrite",
          db: "mydatabase",
        },
        {
          role: "clusterMonitor",
          db: "admin",
        },
      ],
    });
