apiVersion: v1
kind: Service
metadata:
  name: mongodb-exporter-service
spec:
  selector:
    app: mongodb-exporter
  ports:
    - protocol: TCP
      port: 9216
      targetPort: 9216
      nodePort: 31001
  type: NodePort
